package playlist;

import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDropEvent;
import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import playlist.mediainfo.MediaInfo;
        
        

public class Main extends javax.swing.JFrame {
    private DefaultTableModel playlistTableModel;
    public TVFormat TVFormatInstance;
    private Pair<Integer, String> currentTVFormat;
    private Boolean hasDropTarget = false;
    
    /** Creates new form Main */
    public Main() {
        playlistTableModel = new DefaultTableModel(
            new Object [][] { },
            new String [] {
                "Path", "Format", "BitRate(Mb/sec)", "Framerate", "Aspect ratio", "Duration", "TV Format"
            }
        );
        
        initComponents(); // Requires playlistTableModel to be defined
        creatPlaylistButton.setEnabled(false);
        
        TVFormatInstance = TVFormat.getInstance(this);
    }
    
    private int setDropTarget() {
        if (hasDropTarget) {
            return 0;
        }
        
        hasDropTarget = true;
        playlistTableScrollPane.setDropTarget(new DropTarget(){
            @Override
            public synchronized void drop(DropTargetDropEvent dtde) {
                dtde.acceptDrop(DnDConstants.ACTION_COPY_OR_MOVE);
                Transferable t = dtde.getTransferable();
                List fileList = null;
                try {
                    fileList = (List)t.getTransferData(DataFlavor.javaFileListFlavor);
                } catch (UnsupportedFlavorException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                File f;
                String absolutePath;
                
                for (int i = 0; i < fileList.size(); i++){
                    f = (File)fileList.get(i);
                    absolutePath = f.getAbsolutePath();
                    
                    playlistTableModel.insertRow(playlistTableModel.getRowCount(), getVideoData(absolutePath));
                }
                
                creatPlaylistButton.setEnabled(true);
            }
        });
        
        return 0;
    }
    
    private Object[] getVideoData(String path){
        File file = new File(path);
        MediaInfo info = new MediaInfo();
        
        info.open(file);

        String format = info.get("Format");
        
        Float bitRate;
        bitRate = Float.parseFloat(info.get("BitRate")) / 1000000;
        
        String frameRate = info.get("FrameRate");
        Float aspectRatio = Float.parseFloat(info.get("AspectRatio"));
        
        BigInteger duration;
        duration = new BigInteger(info.get("Duration"));
        
        String microduration;
        microduration = String.valueOf(duration.multiply(new BigInteger("10000000")));
        
        info.close();
        info.dispose();
        
        return new Object[]{ path, format, bitRate, frameRate, aspectRatio, microduration, currentTVFormat.getSecond() };
    }
    
    
    /*
     * TVFormat related
     */
    
    public Pair<Integer, String> getTVFormat(){
        return currentTVFormat;
    }
    
    public void setTVFormat(Pair<Integer, String> TVFormat){
        currentTVFormat = TVFormat;
        setDropTarget();
    }
    
    public void showTVFormatFrame(){
        TVFormatInstance.setLocationRelativeTo(this);
        TVFormatInstance.setVisible(true);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creatPlaylistButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        dropVideoNotify = new javax.swing.JLabel();
        playlistTableScrollPane = new javax.swing.JScrollPane();
        playlistTable = new javax.swing.JTable();
        cleanupButton = new javax.swing.JButton();
        TVFormatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batch ingest playlist creator");

        creatPlaylistButton.setText("Создать плейлист");
        creatPlaylistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatPlaylistButtonActionPerformed(evt);
            }
        });

        dropVideoNotify.setForeground(new java.awt.Color(148, 148, 148));
        dropVideoNotify.setText("Перетащите видео-файлы в таблицу");

        playlistTable.setModel(playlistTableModel);
        playlistTableScrollPane.setViewportView(playlistTable);

        cleanupButton.setText("Очистить");
        cleanupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanupButtonActionPerformed(evt);
            }
        });

        TVFormatButton.setText("Формат...");
        TVFormatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TVFormatButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(cleanupButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 249, Short.MAX_VALUE)
                        .add(dropVideoNotify)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(creatPlaylistButton))
                    .add(playlistTableScrollPane)
                    .add(layout.createSequentialGroup()
                        .add(TVFormatButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(TVFormatButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(playlistTableScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(creatPlaylistButton)
                    .add(dropVideoNotify)
                    .add(cleanupButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creatPlaylistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatPlaylistButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creatPlaylistButtonActionPerformed

    private void cleanupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanupButtonActionPerformed
        creatPlaylistButton.setEnabled(false);
        int rows = playlistTableModel.getRowCount() - 1;
        while(rows >= 0) {
            playlistTableModel.removeRow(rows--);
        }
    }//GEN-LAST:event_cleanupButtonActionPerformed

    private void TVFormatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TVFormatButtonActionPerformed
        showTVFormatFrame();
    }//GEN-LAST:event_TVFormatButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx=0; idx<installedLookAndFeels.length; idx++)
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main main = new Main();
                main.setLocationRelativeTo(null);
                main.setVisible(true);
                main.showTVFormatFrame();
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TVFormatButton;
    private javax.swing.JButton cleanupButton;
    private javax.swing.JButton creatPlaylistButton;
    private javax.swing.JLabel dropVideoNotify;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable playlistTable;
    private javax.swing.JScrollPane playlistTableScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
